### ISSUE TITLE
have set arg to logfile , but can not run

### ISSUE THREAD

**Issue by ghost** [xrmx/pyuwsgimemhog#10]
can not run ,  i have set arg to logfile , but can not run

/opt/install/uwsgi-2.0.15-preonline/uwsgi -s 127.0.0.1:3032 -M -p 50 --harakiri=3600 --pythonpath /opt/XENController/PreOnline --chdir /opt/XENController/PreOnline --wsgi-file XenInvoke.py --close-on-exec --log-maxsize=1000000 --daemonize /var/log/vpc_preonline/xeninvoke.log --pidfile=/opt/XENController/PreOnline/uwsgi.pid --buffer-size 655360

[root@testing_pool_api vpc_preonline]# pyuwsgimemhog --logfile xeninvoke.log
Traceback (most recent call last):
  File "/usr/bin/pyuwsgimemhog", line 11, in <module>
    load_entry_point('pyuwsgimemhog==0.3.0', 'console_scripts', 'pyuwsgimemhog')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyuwsgimemhog/cli.py", line 22
    hogs = uwsgimemhog(f, threshold * 1_000_000, normalize)
                                              ^
SyntaxError: invalid syntax

**Comment by xrmx** [comment]
We don't support python 2, that's a syntax error because it does not understand splitting thousands in number constants with _.
